{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ .source.repoURL | required "source.repoURL is required" }}
    targetRevision: {{ .source.targetRevision | default "main" }}
    path: {{ .source.path | required "source.path is required" }}
    {{- if .source.helm }}
    helm:
      {{- if .source.helm.valueFiles }}
      valueFiles:
        {{- range .source.helm.valueFiles }}
        - {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
  destination:
    server: {{ .destination.server | default "https://kubernetes.default.svc" }}
    namespace: {{ .destination.namespace | required "destination.namespace is required" }}
  syncPolicy:
    {{- if .syncPolicy.automated }}
    automated:
      prune: {{ .syncPolicy.automated.prune | default true }}
      selfHeal: {{ .syncPolicy.automated.selfHeal | default true }}
    {{- end }}
    {{- if .syncPolicy.syncOptions }}
    syncOptions:
      {{- range .syncPolicy.syncOptions }}
      - {{ . }}
      {{- end }}
    {{- end }}
{{- end }}

